In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [20]:
le = LogisticRegression()
le.fit(x_train,y_train)
le.score(x_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9722222222222222

In [21]:
svm = SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.987037037037037

In [25]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9796296296296296

In [33]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [35]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [38]:
#new fun to define method
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [39]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9722222222222222

In [41]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.987037037037037

In [42]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9796296296296296

In [44]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [58]:
scores_l = []
scores_svm = []
scores_rf = []
for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index], \
                                    digits.target[train_index],digits.target[test_index]

    scores_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),x_train,x_test,y_train,y_test))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

In [59]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [60]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [61]:
scores_rf

[0.9365609348914858, 0.9499165275459098, 0.9098497495826378]

In [62]:
from sklearn.model_selection import cross_val_score

In [63]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [64]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [66]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.91666667, 0.92777778, 0.95821727, 0.95821727, 0.89972145])

In [67]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target)

array([0.85555556, 0.80277778, 0.89415042, 0.8913649 , 0.83844011])

In [68]:
cross_val_score(RandomForestClassifier(n_estimators=15),digits.data,digits.target)

array([0.91944444, 0.89166667, 0.94428969, 0.93036212, 0.8913649 ])

In [69]:
cross_val_score(RandomForestClassifier(n_estimators=60),digits.data,digits.target)

array([0.93333333, 0.9       , 0.94986072, 0.95821727, 0.94428969])