In [1]:
%%HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/M8Wk85nPH9M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

In [2]:
import numpy as np

In [3]:
a = np.array([5,7,2])

In [4]:
a

array([5, 7, 2])

In [5]:
a.ndim

1

In [6]:
a[0]

5

In [7]:
a[2]

2

In [8]:
a = np.array([[1,2],[5,4],[7,6]],dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [5.+0.j, 4.+0.j],
       [7.+0.j, 6.+0.j]])

In [9]:
a = np.array([[1,2],[5,4],[7,6]])
a

array([[1, 2],
       [5, 4],
       [7, 6]])

In [10]:
a.ndim

2

In [11]:
a.itemsize

4

In [12]:
a.size

6

In [13]:
a.shape

(3, 2)

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
l = range(0,5)

In [17]:
np.arange(1,5)

array([1, 2, 3, 4])

In [18]:
np.arange(1,101,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [19]:
np.linspace(1,5,50)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [20]:
a.reshape(2,3)

array([[1, 2, 5],
       [4, 7, 6]])

In [21]:
a.reshape(6,1)

array([[1],
       [2],
       [5],
       [4],
       [7],
       [6]])

In [22]:
a.ravel()

array([1, 2, 5, 4, 7, 6])

In [23]:
a

array([[1, 2],
       [5, 4],
       [7, 6]])

In [24]:
a.min()

1

In [25]:
a.max()

7

In [26]:
a.sum()

25

In [27]:
a.sum(axis=0)

array([13, 12])

In [28]:
a.sum(axis=1)

array([ 3,  9, 13])

In [29]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [2.23606798, 2.        ],
       [2.64575131, 2.44948974]])

In [30]:
a

array([[1, 2],
       [5, 4],
       [7, 6]])

In [31]:
b = np.array([[6,5],[3,7],[9,2]])
b

array([[6, 5],
       [3, 7],
       [9, 2]])

In [32]:
a * b

array([[ 6, 10],
       [15, 28],
       [63, 12]])

In [33]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [2.23606798, 2.        ],
       [2.64575131, 2.44948974]])

In [34]:
np.std(b)

2.357022603955158

In [35]:
a + b

array([[ 7,  7],
       [ 8, 11],
       [16,  8]])

In [36]:
a / b

array([[0.16666667, 0.4       ],
       [1.66666667, 0.57142857],
       [0.77777778, 3.        ]])

In [37]:
a = np.array([[1,2],[5,4]])
a

array([[1, 2],
       [5, 4]])

In [38]:
b = np.array([[1,2],[5,4]])
b

array([[1, 2],
       [5, 4]])

In [39]:
a @ b

array([[11, 10],
       [25, 26]])

# pandas module

In [40]:
import pandas as pd
df = pd.read_csv('E:/data science/data sets/educional data in india.csv')

In [41]:
print(dir(pd))

['BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_hashtable', '_lib', '_libs', '_np_version_under1p14', '_np_version_under1p15', '_np_version_under1p16', '_np_version_under1p17', '_np_version_under1p18', '_testing', '_tslib', '_typing', '_version', 'api', 'array

In [42]:
print(dir(df))

['AC_YEAR', 'AREA_SQKM', 'BLOCKS', 'CLUSTERS', 'DISTCD', 'DISTNAME', 'DISTRICTS', 'FEMALE_LIT', 'GROWTHRATE', 'MALE_LIT', 'OVERALL_LI', 'POPULATION_0_6', 'P_SC_POP', 'P_ST_POP', 'P_URB_POP', 'SCH1', 'SCH1G', 'SCH1GA', 'SCH1GR', 'SCH1M', 'SCH1P', 'SCH1PR', 'SCH2', 'SCH2G', 'SCH2GA', 'SCH2GR', 'SCH2M', 'SCH2P', 'SCH2PR', 'SCH3', 'SCH3G', 'SCH3GA', 'SCH3GR', 'SCH3M', 'SCH3P', 'SCH3PR', 'SCH4', 'SCH4G', 'SCH4GA', 'SCH4GR', 'SCH4M', 'SCH4P', 'SCH4PR', 'SCH5', 'SCH5G', 'SCH5GA', 'SCH5GR', 'SCH5M', 'SCH5P', 'SCH5PR', 'SCH6', 'SCH6G', 'SCH6GA', 'SCH6GR', 'SCH6M', 'SCH6P', 'SCH6PR', 'SCH7', 'SCH7G', 'SCH7GA', 'SCH7GR', 'SCH7M', 'SCH7P', 'SCH7PR', 'SCH9', 'SCH9G', 'SCH9GA', 'SCH9GR', 'SCH9M', 'SCH9P', 'SCH9PR', 'SCHBOY1', 'SCHBOY2', 'SCHBOY3', 'SCHBOY4', 'SCHBOY5', 'SCHBOY6', 'SCHBOY7', 'SCHBOY9', 'SCHBOYTOT', 'SCHGIR1', 'SCHGIR2', 'SCHGIR3', 'SCHGIR4', 'SCHGIR5', 'SCHGIR6', 'SCHTOT', 'SCHTOTG', 'SCHTOTGA', 'SCHTOTGR', 'SCHTOTM', 'SCHTOTP', 'SCHTOTPR', 'SEXRATIO', 'STATCD', 'STATNAME', 'T', 'TOT

In [43]:
df

AC_YEAR  STATCD  DISTCD         STATNAME     DISTNAME  DISTRICTS  BLOCKS  \
0    2015-16       1     101  JAMMU & KASHMIR      KUPWARA          1      13   
1    2015-16       1     102  JAMMU & KASHMIR     BARAMULA          1      18   
2    2015-16       1     103  JAMMU & KASHMIR     SRINAGAR          1       8   
3    2015-16       1     104  JAMMU & KASHMIR       BADGAM          1      13   
4    2015-16       1     105  JAMMU & KASHMIR      PULWAMA          1       8   
..       ...     ...     ...              ...          ...        ...     ...   
675  2015-16      36    3606        TELANGANA  RANGA REDDY          1      37   
676  2015-16      36    3607        TELANGANA  MAHBUBNAGAR          1      64   
677  2015-16      36    3608        TELANGANA     NALGONDA          1      59   
678  2015-16      36    3609        TELANGANA     WARANGAL          1      51   
679  2015-16      36    3610        TELANGANA      KHAMMAM          1      41   

     VILLAGES  CLUSTERS  TOTPOPULAT  ...  UUNI_ALL  UUNI_SC  UUNI_ST  \
0         391       104    875564.0  ...     21322       26     2594   
1         678       144   1015503.0  ...     17307        0     1571   
2          94        65   1269751.0  ...      5444       31      408   
3         523       104    735753.0  ...     12469       18      857   
4         359        64    570060.0  ...      7408       17      855   
..        ...       ...         ...  ...       ...      ...      ...   
675       876       137   5296396.0  ...     93203    25534     9457   
676      1458       230   4042191.0  ...    134277    31001    14590   
677      1117       216   3483648.0  ...     96804    26577    14015   
678       993       211   3522644.0  ...     92224    23172    23525   
679       783       185   2798214.0  ...     70234    15593    25217   

     TOTCLS1G  TOTCLS2G  TOTCLS3G  TOTCLS4G  TOTCLS5G  TOTCLS6G  TOTCLS7G  
0        3489      5315        27        62        23       852       239  
1        4127      5800       210        53        30      1665       360  
2         817      3284       886        11         0      2873        40  
3        2290      3837       119        45         8      1035       325  
4        1688      2584       151        67         5      1101       209  
..        ...       ...       ...       ...       ...       ...       ...  
675      7224      8298       529         0       121     15458      3337  
676      8936      7007       179         0        44      3730      3327  
677      7592      4534       103         0       208      4026      3049  
678      6674      4677       153         0       207      7035      3060  
679      6047      4015       104         0        32      3103      2228  

[680 rows x 819 columns]

In [44]:
df[df.STATNAME=='GUJARAT']

AC_YEAR  STATCD  DISTCD STATNAME          DISTNAME  DISTRICTS  BLOCKS  \
497  2015-16      24    2401  GUJARAT           KACHCHH          1      10   
498  2015-16      24    2402  GUJARAT      BANAS KANTHA          1      14   
499  2015-16      24    2403  GUJARAT             PATAN          1       9   
500  2015-16      24    2404  GUJARAT          MAHESANA          1      10   
501  2015-16      24    2405  GUJARAT      SABAR KANTHA          1       8   
502  2015-16      24    2406  GUJARAT       GANDHINAGAR          1       4   
503  2015-16      24    2407  GUJARAT         AHMEDABAD          1      11   
504  2015-16      24    2408  GUJARAT     SURENDRANAGAR          1      10   
505  2015-16      24    2409  GUJARAT            RAJKOT          1      12   
506  2015-16      24    2410  GUJARAT          JAMNAGAR          1       6   
507  2015-16      24    2411  GUJARAT         PORBANDAR          1       3   
508  2015-16      24    2412  GUJARAT          JUNAGADH          1      10   
509  2015-16      24    2413  GUJARAT            AMRELI          1      11   
510  2015-16      24    2414  GUJARAT         BHAVNAGAR          1      10   
511  2015-16      24    2415  GUJARAT             ANAND          1       8   
512  2015-16      24    2416  GUJARAT             KHEDA          1      10   
513  2015-16      24    2417  GUJARAT      PANCH MAHALS          1       7   
514  2015-16      24    2418  GUJARAT             DOHAD          1       8   
515  2015-16      24    2419  GUJARAT          VADODARA          1       9   
516  2015-16      24    2420  GUJARAT           NARMADA          1       5   
517  2015-16      24    2421  GUJARAT           BHARUCH          1       9   
518  2015-16      24    2422  GUJARAT             SURAT          1      10   
519  2015-16      24    2423  GUJARAT         THE DANGS          1       3   
520  2015-16      24    2424  GUJARAT           NAVSARI          1       6   
521  2015-16      24    2425  GUJARAT            VALSAD          1       6   
522  2015-16      24    2426  GUJARAT              TAPI          1       7   
523  2015-16      24    2427  GUJARAT          ARAVALLI          1       6   
524  2015-16      24    2428  GUJARAT             BOTAD          1       4   
525  2015-16      24    2429  GUJARAT  DEVBHOOMI DWARKA          1       4   
526  2015-16      24    2430  GUJARAT       GIR SOMNATH          1       6   
527  2015-16      24    2431  GUJARAT         MAHISAGAR          1       6   
528  2015-16      24    2432  GUJARAT      CHHOTAUDEPUR          1       6   
529  2015-16      24    2433  GUJARAT             MORBI          1       5   

     VILLAGES  CLUSTERS  TOTPOPULAT  ...  UUNI_ALL  UUNI_SC  UUNI_ST  \
497      1011       247   2090313.0  ...     69860    12998     1664   
498      1377       282   3116045.0  ...    156052    15067    16983   
499       679       109   1342746.0  ...     67114     6314      770   
500       730       146   2027727.0  ...     77319     4697      586   
501       684       167   2427346.0  ...     56986     5038    19985   
502       490        96   1387478.0  ...     46753     2761     1173   
503       683       186   7208200.0  ...    106334    14533     3090   
504       602       124   1755873.0  ...     68719     6922     1631   
505       640       150   3799770.0  ...     63093     9852     1552   
506       432       110   2159130.0  ...     19000     3259      506   
507       163        48    586062.0  ...     20550     2532      444   
508       521       100   2742291.0  ...     36651     5741      582   
509       626       120   1513614.0  ...     50809     6016      503   
510       697       147   2877961.0  ...    105158     5354      789   
511       362       164   2090276.0  ...     77625     3663     1934   
512       558       179   2298934.0  ...     83196     3607     2219   
513       578       171   2388267.0  ...     62088     1878    16337   
514       736       175   2126558.0  ...     71267     1

In [45]:
df[df.STATNAME==df.STATNAME.min()]

AC_YEAR  STATCD  DISTCD       STATNAME                   DISTNAME  \
667  2015-16      35    3501  A & N ISLANDS                   ANDAMANS   
668  2015-16      35    3502  A & N ISLANDS                   NICOBARS   
669  2015-16      35    3503  A & N ISLANDS  MIDDLE AND NORTH ANDAMANS   

     DISTRICTS  BLOCKS  VILLAGES  CLUSTERS  TOTPOPULAT  ...  UUNI_ALL  \
667          1       3        80        16    237586.0  ...      4501   
668          1       3        42         8     36819.0  ...      1325   
669          1       3        76        13    105539.0  ...      5748   

     UUNI_SC  UUNI_ST  TOTCLS1G  TOTCLS2G  TOTCLS3G  TOTCLS4G  TOTCLS5G  \
667        0      144       393       366       445         0        24   
668        0      991       105        57        21         0        24   
669       56       34       397       300       103         0        58   

     TOTCLS6G  TOTCLS7G  
667       192         0  
668        71         0  
669       199         0  

[3 rows x 819 columns]

In [46]:
df['STATNAME'].max()

'WEST BENGAL'

In [47]:
df['STATNAME'].min()

'A & N ISLANDS'

In [48]:
df['STATNAME'][df['DISTCD']==2403]

499    GUJARAT
Name: STATNAME, dtype: object

In [49]:
df.describe()

STATCD       DISTCD  DISTRICTS      BLOCKS     VILLAGES  \
count  680.000000   680.000000      680.0  680.000000   680.000000   
mean    17.292647  1745.976471        1.0   10.760294   874.614706   
std      9.451743   944.257509        0.0    9.585360   622.711657   
min      1.000000   101.000000        1.0    1.000000     6.000000   
25%      9.000000   937.750000        1.0    5.000000   390.750000   
50%     18.000000  1823.500000        1.0    8.000000   785.500000   
75%     24.000000  2413.250000        1.0   13.000000  1204.250000   
max     36.000000  3610.000000        1.0   66.000000  3963.000000   

         CLUSTERS    TOTPOPULAT   P_URB_POP  POPULATION_0_6  GROWTHRATE  ...  \
count  680.000000  6.340000e+02  631.000000    6.330000e+02  634.000000  ...   
mean   121.226471  1.899024e+06   24.819255    2.494264e+05   17.627886  ...   
std     94.040172  1.547475e+06   19.093744    1.985112e+05   11.346020  ...   
min      1.000000  7.948000e+03  -25.350000    1.103980e+03  -58.390000  ...   
25%     56.750000  8.226940e+05   11.375000    1.087804e+05   12.052500  ...   
50%    101.000000  1.564392e+06   19.500000    2.040779e+05   17.055000  ...   
75%    162.500000  2.587520e+06   32.420000    3.378675e+05   22.740000  ...   
max    592.000000  1.105413e+07  100.000000    1.256855e+06  111.010000  ...   

            UUNI_ALL        UUNI_SC       UUNI_ST      TOTCLS1G      TOTCLS2G  \
count     680.000000     680.000000    680.000000    680.000000    680.000000   
mean    46465.307353   11444.252941   5485.394118   4530.914706   3180.994118   
std     57485.560854   16548.586787   9455.045146   3881.154776   3332.333288   
min         0.000000       0.000000      0.000000     24.000000      0.000000   
25%      7534.000000     736.750000    165.250000   1903.750000    674.750000   
50%     32185.500000    6816.500000   1321.000000   3555.000000   1922.500000   
75%     60492.750000   15300.500000   6183.500000   5944.250000   4870.500000   
max    511213.000000  153047.000000  68723.000000  24728.000000  25677.000000   

           TOTCLS3G     TOTCLS4G     TOTCLS5G      TOTCLS6G      TOTCLS7G  
count    680.000000   680.000000   680.000000    680.000000    680.000000  
mean     764.154412   898.879412   391.352941    717.679412    385.957353  
std     1330.305834  1425.313485   820.868908   1194.616699    935.196354  
min        0.000000     0.000000     0.000000      0.000000      0.000000  
25%       68.000000    17.000000    17.000000    137.000000     20.750000  
50%      249.500000   129.500000    70.500000    407.000000    115.500000  
75%      887.750000  1383.000000   462.000000    824.500000    319.500000  
max    16053.000000  8590.000000  8074.000000  15458.000000  11904.000000  

[8 rows x 816 columns]

In [50]:
df['DISTCD'].max()

3610

In [51]:
df.drop(columns=['TOTPOPULAT'],axis=1,inplace=True)

In [52]:
df

AC_YEAR  STATCD  DISTCD         STATNAME     DISTNAME  DISTRICTS  BLOCKS  \
0    2015-16       1     101  JAMMU & KASHMIR      KUPWARA          1      13   
1    2015-16       1     102  JAMMU & KASHMIR     BARAMULA          1      18   
2    2015-16       1     103  JAMMU & KASHMIR     SRINAGAR          1       8   
3    2015-16       1     104  JAMMU & KASHMIR       BADGAM          1      13   
4    2015-16       1     105  JAMMU & KASHMIR      PULWAMA          1       8   
..       ...     ...     ...              ...          ...        ...     ...   
675  2015-16      36    3606        TELANGANA  RANGA REDDY          1      37   
676  2015-16      36    3607        TELANGANA  MAHBUBNAGAR          1      64   
677  2015-16      36    3608        TELANGANA     NALGONDA          1      59   
678  2015-16      36    3609        TELANGANA     WARANGAL          1      51   
679  2015-16      36    3610        TELANGANA      KHAMMAM          1      41   

     VILLAGES  CLUSTERS  P_URB_POP  ...  UUNI_ALL  UUNI_SC  UUNI_ST  TOTCLS1G  \
0         391       104      11.33  ...     21322       26     2594      3489   
1         678       144      17.19  ...     17307        0     1571      4127   
2          94        65      98.73  ...      5444       31      408       817   
3         523       104      11.74  ...     12469       18      857      2290   
4         359        64      13.80  ...      7408       17      855      1688   
..        ...       ...        ...  ...       ...      ...      ...       ...   
675       876       137      70.32  ...     93203    25534     9457      7224   
676      1458       230      15.00  ...    134277    31001    14590      8936   
677      1117       216      19.00  ...     96804    26577    14015      7592   
678       993       211      28.34  ...     92224    23172    23525      6674   
679       783       185      23.43  ...     70234    15593    25217      6047   

     TOTCLS2G  TOTCLS3G  TOTCLS4G  TOTCLS5G  TOTCLS6G  TOTCLS7G  
0        5315        27        62        23       852       239  
1        5800       210        53        30      1665       360  
2        3284       886        11         0      2873        40  
3        3837       119        45         8      1035       325  
4        2584       151        67         5      1101       209  
..        ...       ...       ...       ...       ...       ...  
675      8298       529         0       121     15458      3337  
676      7007       179         0        44      3730      3327  
677      4534       103         0       208      4026      3049  
678      4677       153         0       207      7035      3060  
679      4015       104         0        32      3103      2228  

[680 rows x 818 columns]

In [53]:
weighes = {
    'day':['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature':[32,85,74,95,46,75],
    'windspeed':[6,7,5,1,3,4],
    'event':['rain','sunny','snow','snow','rain','sunny']
}
df = pd.DataFrame(weighes)
df

day  temperature  windspeed  event
0  1/1/2017           32          6   rain
1  1/2/2017           85          7  sunny
2  1/3/2017           74          5   snow
3  1/4/2017           95          1   snow
4  1/5/2017           46          3   rain
5  1/6/2017           75          4  sunny

In [54]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [55]:
df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [56]:
df.event

0     rain
1    sunny
2     snow
3     snow
4     rain
5    sunny
Name: event, dtype: object

In [57]:
type(df['event'])

pandas.core.series.Series

In [58]:
df

day  temperature  windspeed  event
0  1/1/2017           32          6   rain
1  1/2/2017           85          7  sunny
2  1/3/2017           74          5   snow
3  1/4/2017           95          1   snow
4  1/5/2017           46          3   rain
5  1/6/2017           75          4  sunny

In [59]:
df[['day','event','temperature']]

day  event  temperature
0  1/1/2017   rain           32
1  1/2/2017  sunny           85
2  1/3/2017   snow           74
3  1/4/2017   snow           95
4  1/5/2017   rain           46
5  1/6/2017  sunny           75

In [60]:
df.head()

day  temperature  windspeed  event
0  1/1/2017           32          6   rain
1  1/2/2017           85          7  sunny
2  1/3/2017           74          5   snow
3  1/4/2017           95          1   snow
4  1/5/2017           46          3   rain

In [61]:
df.head(2)

day  temperature  windspeed  event
0  1/1/2017           32          6   rain
1  1/2/2017           85          7  sunny

In [62]:
df.head(3)

day  temperature  windspeed  event
0  1/1/2017           32          6   rain
1  1/2/2017           85          7  sunny
2  1/3/2017           74          5   snow

In [63]:
df.tail()

day  temperature  windspeed  event
1  1/2/2017           85          7  sunny
2  1/3/2017           74          5   snow
3  1/4/2017           95          1   snow
4  1/5/2017           46          3   rain
5  1/6/2017           75          4  sunny

In [64]:
df.tail(1)

day  temperature  windspeed  event
5  1/6/2017           75          4  sunny

In [65]:
df

day  temperature  windspeed  event
0  1/1/2017           32          6   rain
1  1/2/2017           85          7  sunny
2  1/3/2017           74          5   snow
3  1/4/2017           95          1   snow
4  1/5/2017           46          3   rain
5  1/6/2017           75          4  sunny

In [66]:
df['event'].max()

'sunny'

In [67]:
df['windspeed'].min()

1

In [68]:
df.describe()

temperature  windspeed
count     6.000000   6.000000
mean     67.833333   4.333333
std      24.011803   2.160247
min      32.000000   1.000000
25%      53.000000   3.250000
50%      74.500000   4.500000
75%      82.500000   5.750000
max      95.000000   7.000000

In [69]:
df[df.temperature>=50]

day  temperature  windspeed  event
1  1/2/2017           85          7  sunny
2  1/3/2017           74          5   snow
3  1/4/2017           95          1   snow
5  1/6/2017           75          4  sunny

In [70]:
df[df.temperature==df.temperature.max()]

day  temperature  windspeed event
3  1/4/2017           95          1  snow

In [71]:
df[df.windspeed==df.windspeed.min()]

day  temperature  windspeed event
3  1/4/2017           95          1  snow

In [72]:
df[['day','temperature']][df.temperature==df.temperature.max()]

day  temperature
3  1/4/2017           95

In [73]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [74]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [75]:
df.set_index('day',inplace=True)

In [76]:
df

temperature  windspeed  event
day                                    
1/1/2017           32          6   rain
1/2/2017           85          7  sunny
1/3/2017           74          5   snow
1/4/2017           95          1   snow
1/5/2017           46          3   rain
1/6/2017           75          4  sunny

In [77]:
df.loc['1/3/2017']
# df.loc[1:3]

temperature      74
windspeed         5
event          snow
Name: 1/3/2017, dtype: object

In [86]:
df.reset_index(inplace=True)

In [87]:
df

index       day  temperature  winspeed  event
0      0  1/1/2017           85        45   rain
1      1  1/2/2017           45        65  sunny
2      2  1/3/2017           75        94   modi
3      3  1/4/2017           95        71   meet
4      4  1/5/2017           65        21   dipu

In [88]:
df.loc[:]

index       day  temperature  winspeed  event
0      0  1/1/2017           85        45   rain
1      1  1/2/2017           45        65  sunny
2      2  1/3/2017           75        94   modi
3      3  1/4/2017           95        71   meet
4      4  1/5/2017           65        21   dipu

In [89]:
df.iloc[3:5]

index       day  temperature  winspeed event
3      3  1/4/2017           95        71  meet
4      4  1/5/2017           65        21  dipu

In [90]:
df.loc[3:5]

index       day  temperature  winspeed event
3      3  1/4/2017           95        71  meet
4      4  1/5/2017           65        21  dipu

In [91]:
#list in tuples
weather_data = [
    ('1/1/2017',85,45,'rain'),
    ('1/2/2017',45,65,'sunny'),
    ('1/3/2017',75,94,'modi'),
    ('1/4/2017',95,71,'meet'),
    ('1/5/2017',65,21,'dipu')
]
df = pd.DataFrame(weather_data,columns=['day','temperature','winspeed','event'])

In [92]:
df

day  temperature  winspeed  event
0  1/1/2017           85        45   rain
1  1/2/2017           45        65  sunny
2  1/3/2017           75        94   modi
3  1/4/2017           95        71   meet
4  1/5/2017           65        21   dipu

In [119]:
df = pd.read_csv('E:/data science/data sets/educional data in india.csv')
df

AC_YEAR  STATCD  DISTCD         STATNAME     DISTNAME  DISTRICTS  BLOCKS  \
0    2015-16       1     101  JAMMU & KASHMIR      KUPWARA          1      13   
1    2015-16       1     102  JAMMU & KASHMIR     BARAMULA          1      18   
2    2015-16       1     103  JAMMU & KASHMIR     SRINAGAR          1       8   
3    2015-16       1     104  JAMMU & KASHMIR       BADGAM          1      13   
4    2015-16       1     105  JAMMU & KASHMIR      PULWAMA          1       8   
..       ...     ...     ...              ...          ...        ...     ...   
675  2015-16      36    3606        TELANGANA  RANGA REDDY          1      37   
676  2015-16      36    3607        TELANGANA  MAHBUBNAGAR          1      64   
677  2015-16      36    3608        TELANGANA     NALGONDA          1      59   
678  2015-16      36    3609        TELANGANA     WARANGAL          1      51   
679  2015-16      36    3610        TELANGANA      KHAMMAM          1      41   

     VILLAGES  CLUSTERS  TOTPOPULAT  ...  UUNI_ALL  UUNI_SC  UUNI_ST  \
0         391       104    875564.0  ...     21322       26     2594   
1         678       144   1015503.0  ...     17307        0     1571   
2          94        65   1269751.0  ...      5444       31      408   
3         523       104    735753.0  ...     12469       18      857   
4         359        64    570060.0  ...      7408       17      855   
..        ...       ...         ...  ...       ...      ...      ...   
675       876       137   5296396.0  ...     93203    25534     9457   
676      1458       230   4042191.0  ...    134277    31001    14590   
677      1117       216   3483648.0  ...     96804    26577    14015   
678       993       211   3522644.0  ...     92224    23172    23525   
679       783       185   2798214.0  ...     70234    15593    25217   

     TOTCLS1G  TOTCLS2G  TOTCLS3G  TOTCLS4G  TOTCLS5G  TOTCLS6G  TOTCLS7G  
0        3489      5315        27        62        23       852       239  
1        4127      5800       210        53        30      1665       360  
2         817      3284       886        11         0      2873        40  
3        2290      3837       119        45         8      1035       325  
4        1688      2584       151        67         5      1101       209  
..        ...       ...       ...       ...       ...       ...       ...  
675      7224      8298       529         0       121     15458      3337  
676      8936      7007       179         0        44      3730      3327  
677      7592      4534       103         0       208      4026      3049  
678      6674      4677       153         0       207      7035      3060  
679      6047      4015       104         0        32      3103      2228  

[680 rows x 819 columns]

In [121]:
ds = df[['AC_YEAR','STATCD','DISTCD','STATNAME','DISTNAME']] #jo aa apde vadhre padti columns hoy tare selected columns rakhavi hoy
                                                             #tare aa methods use kari sakay
ds

AC_YEAR  STATCD  DISTCD         STATNAME     DISTNAME
0    2015-16       1     101  JAMMU & KASHMIR      KUPWARA
1    2015-16       1     102  JAMMU & KASHMIR     BARAMULA
2    2015-16       1     103  JAMMU & KASHMIR     SRINAGAR
3    2015-16       1     104  JAMMU & KASHMIR       BADGAM
4    2015-16       1     105  JAMMU & KASHMIR      PULWAMA
..       ...     ...     ...              ...          ...
675  2015-16      36    3606        TELANGANA  RANGA REDDY
676  2015-16      36    3607        TELANGANA  MAHBUBNAGAR
677  2015-16      36    3608        TELANGANA     NALGONDA
678  2015-16      36    3609        TELANGANA     WARANGAL
679  2015-16      36    3610        TELANGANA      KHAMMAM

[680 rows x 5 columns]

In [113]:
dg = ds[ds['STATNAME']=='GUJARAT']
dg

AC_YEAR  STATCD  DISTCD STATNAME          DISTNAME
497  2015-16      24    2401  GUJARAT           KACHCHH
498  2015-16      24    2402  GUJARAT      BANAS KANTHA
499  2015-16      24    2403  GUJARAT             PATAN
500  2015-16      24    2404  GUJARAT          MAHESANA
501  2015-16      24    2405  GUJARAT      SABAR KANTHA
502  2015-16      24    2406  GUJARAT       GANDHINAGAR
503  2015-16      24    2407  GUJARAT         AHMEDABAD
504  2015-16      24    2408  GUJARAT     SURENDRANAGAR
505  2015-16      24    2409  GUJARAT            RAJKOT
506  2015-16      24    2410  GUJARAT          JAMNAGAR
507  2015-16      24    2411  GUJARAT         PORBANDAR
508  2015-16      24    2412  GUJARAT          JUNAGADH
509  2015-16      24    2413  GUJARAT            AMRELI
510  2015-16      24    2414  GUJARAT         BHAVNAGAR
511  2015-16      24    2415  GUJARAT             ANAND
512  2015-16      24    2416  GUJARAT             KHEDA
513  2015-16      24    2417  GUJARAT      PANCH MAHALS
514  2015-16      24    2418  GUJARAT             DOHAD
515  2015-16      24    2419  GUJARAT          VADODARA
516  2015-16      24    2420  GUJARAT           NARMADA
517  2015-16      24    2421  GUJARAT           BHARUCH
518  2015-16      24    2422  GUJARAT             SURAT
519  2015-16      24    2423  GUJARAT         THE DANGS
520  2015-16      24    2424  GUJARAT           NAVSARI
521  2015-16      24    2425  GUJARAT            VALSAD
522  2015-16      24    2426  GUJARAT              TAPI
523  2015-16      24    2427  GUJARAT          ARAVALLI
524  2015-16      24    2428  GUJARAT             BOTAD
525  2015-16      24    2429  GUJARAT  DEVBHOOMI DWARKA
526  2015-16      24    2430  GUJARAT       GIR SOMNATH
527  2015-16      24    2431  GUJARAT         MAHISAGAR
528  2015-16      24    2432  GUJARAT      CHHOTAUDEPUR
529  2015-16      24    2433  GUJARAT             MORBI

In [122]:
df = pd.read_csv('E:/data science/data sets/educional data in india.csv',skiprows=600,na_values=['not avialble'])
df

2015-16  29  2918  KARNATAKA             TUMKUR  1   6  1450  179  \
0   2015-16  29  2919  KARNATAKA              KOLAR  1   6  1506  145   
1   2015-16  29  2920  KARNATAKA  BANGALORE U SOUTH  1   5   584   96   
2   2015-16  29  2921  KARNATAKA    BANGALORE RURAL  1   4   899   89   
3   2015-16  29  2922  KARNATAKA             MANDYA  1   8  1355  145   
4   2015-16  29  2923  KARNATAKA             HASSAN  1   8  1971  208   
..      ...  ..   ...        ...                ... ..  ..   ...  ...   
75  2015-16  36  3606  TELANGANA        RANGA REDDY  1  37   876  137   
76  2015-16  36  3607  TELANGANA        MAHBUBNAGAR  1  64  1458  230   
77  2015-16  36  3608  TELANGANA           NALGONDA  1  59  1117  216   
78  2015-16  36  3609  TELANGANA           WARANGAL  1  51   993  211   
79  2015-16  36  3610  TELANGANA            KHAMMAM  1  41   783  185   

      2681449  ...   32603   7894   2391  3322.1  6203.1  0.204  73.1  9.11  \
0   1540231.0  ...   31578  13275   2624    3048    5744     92    50     0   
1         NaN  ...   39409  14532   2137    2935   10077   8947    12    26   
2    987257.0  ...   22663   8224   1932    1775    3403     79    16     6   
3   1808680.0  ...   49777  10116   1028    2523    7371     50    95     6   
4   1776221.0  ...   20748   6880    938    3329    7410      0   104     2   
..        ...  ...     ...    ...    ...     ...     ...    ...   ...   ...   
75  5296396.0  ...   93203  25534   9457    7224    8298    529     0   121   
76  4042191.0  ...  134277  31001  14590    8936    7007    179     0    44   
77  3483648.0  ...   96804  26577  14015    7592    4534    103     0   208   
78  3522644.0  ...   92224  23172  23525    6674    4677    153     0   207   
79  2798214.0  ...   70234  15593  25217    6047    4015    104     0    32   

    578.1  43.5  
0    1147    83  
1    8078   214  
2    1138    33  
3     479   117  
4     487   101  
..    ...   ...  
75  15458  3337  
76   3730  3327  
77   4026  3049  
78   7035  3060  
79   3103  2228  

[80 rows x 819 columns]

In [123]:
df.iloc[55:60]

2015-16  29  2918   KARNATAKA          TUMKUR  1   6  1450  179  \
55  2015-16  33  3324  TAMIL NADU         MADURAI  1  15   693  165   
56  2015-16  33  3325  TAMIL NADU           THENI  1   8   102   80   
57  2015-16  33  3326  TAMIL NADU    VIRUDHUNAGAR  1  11   466  134   
58  2015-16  33  3327  TAMIL NADU  RAMANATHAPURAM  1  11  1042  121   
59  2015-16  33  3328  TAMIL NADU    THOOTHUKKUDI  1  13   637  108   

      2681449  ...  32603   7894  2391  3322.1  6203.1  0.204  73.1  9.11  \
55  3041038.0  ...  15811   6930    59    6918    3452   3115     6  1299   
56  1243684.0  ...  33952  11312   187    2713    1824    845     0   617   
57  1943309.0  ...  42267  14122    72    5096    2007    878    12  1183   
58  1337560.0  ...  23306   7164    15    3886    1735    773     3   700   
59  1738376.0  ...  31972   9981   240    4523    2366   1025    12   977   

    578.1  43.5  
55    861   497  
56    327   207  
57    455   460  
58    486   336  
59    622   317  

[5 rows x 819 columns]

In [124]:
#list in tuples

weather_data = [
    ('1/1/2017',85,45,'rain'),
    ('1/2/2017',45,65,'sunny'),
    ('1/3/2017',75,94,'modi'),
    ('1/4/2017',95,71,'nan'),
    ('1/5/2017',65,21,'dipu')
]
df = pd.DataFrame(weather_data,columns=['day','temperature','winspeed','event'])

In [125]:
df

day  temperature  winspeed  event
0  1/1/2017           85        45   rain
1  1/2/2017           45        65  sunny
2  1/3/2017           75        94   modi
3  1/4/2017           95        71    nan
4  1/5/2017           65        21   dipu

In [127]:
def conver_cell(cell):
    if cell == 'BADGAM':
        return 'modi bhargav'
    return cell

df = pd.read_csv('E:/data science/data sets/educional data in india.csv',converters = {
    'DISTNAME':conver_cell
})
df

AC_YEAR  STATCD  DISTCD         STATNAME      DISTNAME  DISTRICTS  \
0    2015-16       1     101  JAMMU & KASHMIR       KUPWARA          1   
1    2015-16       1     102  JAMMU & KASHMIR      BARAMULA          1   
2    2015-16       1     103  JAMMU & KASHMIR      SRINAGAR          1   
3    2015-16       1     104  JAMMU & KASHMIR  modi bhargav          1   
4    2015-16       1     105  JAMMU & KASHMIR       PULWAMA          1   
..       ...     ...     ...              ...           ...        ...   
675  2015-16      36    3606        TELANGANA   RANGA REDDY          1   
676  2015-16      36    3607        TELANGANA   MAHBUBNAGAR          1   
677  2015-16      36    3608        TELANGANA      NALGONDA          1   
678  2015-16      36    3609        TELANGANA      WARANGAL          1   
679  2015-16      36    3610        TELANGANA       KHAMMAM          1   

     BLOCKS  VILLAGES  CLUSTERS  TOTPOPULAT  ...  UUNI_ALL  UUNI_SC  UUNI_ST  \
0        13       391       104    875564.0  ...     21322       26     2594   
1        18       678       144   1015503.0  ...     17307        0     1571   
2         8        94        65   1269751.0  ...      5444       31      408   
3        13       523       104    735753.0  ...     12469       18      857   
4         8       359        64    570060.0  ...      7408       17      855   
..      ...       ...       ...         ...  ...       ...      ...      ...   
675      37       876       137   5296396.0  ...     93203    25534     9457   
676      64      1458       230   4042191.0  ...    134277    31001    14590   
677      59      1117       216   3483648.0  ...     96804    26577    14015   
678      51       993       211   3522644.0  ...     92224    23172    23525   
679      41       783       185   2798214.0  ...     70234    15593    25217   

     TOTCLS1G  TOTCLS2G  TOTCLS3G  TOTCLS4G  TOTCLS5G  TOTCLS6G  TOTCLS7G  
0        3489      5315        27        62        23       852       239  
1        4127      5800       210        53        30      1665       360  
2         817      3284       886        11         0      2873        40  
3        2290      3837       119        45         8      1035       325  
4        1688      2584       151        67         5      1101       209  
..        ...       ...       ...       ...       ...       ...       ...  
675      7224      8298       529         0       121     15458      3337  
676      8936      7007       179         0        44      3730      3327  
677      7592      4534       103         0       208      4026      3049  
678      6674      4677       153         0       207      7035      3060  
679      6047      4015       104         0        32      3103      2228  

[680 rows x 819 columns]

In [130]:
#list in tuples

weather_data = [
    ('1/1/2017',85,45,'rain'),
    ('1/2/2017',45,'NaN','sunny'),
    ('1/3/2017',75,94,'modi'),
    ('1/4/2017',95,71,'NaN'),
    ('NaN',65,21,'dipu'),
    ('1/6/2017',95,41,'NaN'),
    ('1/7/2018',85,64,'sila'),
    ('1/9/2019','NaN',35,'muni')
]
df = pd.DataFrame(weather_data,columns=['day','temperature','winspeed','event'])
df

day temperature winspeed  event
0  1/1/2017          85       45   rain
1  1/2/2017          45      NaN  sunny
2  1/3/2017          75       94   modi
3  1/4/2017          95       71    NaN
4       NaN          65       21   dipu
5  1/6/2017          95       41    NaN
6  1/7/2018          85       64   sila
7  1/9/2019         NaN       35   muni

In [132]:
new_data = df.fillna(0)
new_data

day temperature winspeed  event
0  1/1/2017          85       45   rain
1  1/2/2017          45      NaN  sunny
2  1/3/2017          75       94   modi
3  1/4/2017          95       71    NaN
4       NaN          65       21   dipu
5  1/6/2017          95       41    NaN
6  1/7/2018          85       64   sila
7  1/9/2019         NaN       35   muni

In [133]:
type(df.day[0])

str

In [136]:
df = pd.read_excel('E:/data science/data sets/whethers.xlsx')
df

date  temperature  windspeed   city
0 2017-01-01           32          6  patan
1 2017-02-01           85          7   ahem
2 2017-03-01           28          5  surat
3 2017-01-12           42          7  patan
4 2017-02-12           32          1   ahem
5 2017-03-12           51          6  surat
6 2017-01-02           75          8  patan
7 2017-02-02           94          9   ahem
8 2017-03-02           15          2  surat

In [138]:
def conver_event_cell(cell):
    if cell == 'No Event':
        return 'modi'
    return cell
df = pd.read_excel('E:/data science/data sets/whethers.xlsx',converters={
    'event':conver_event_cell
})
df

date  temperature  windspeed   city
0 2017-01-01           32          6  patan
1 2017-02-01           85          7   ahem
2 2017-03-01           28          5  surat
3 2017-01-12           42          7  patan
4 2017-02-12           32          1   ahem
5 2017-03-12           51          6  surat
6 2017-01-02           75          8  patan
7 2017-02-02           94          9   ahem
8 2017-03-02           15          2  surat

In [140]:
df = pd.read_excel('E:/data science/data sets/whethers.xlsx',parse_dates=['date'])
df.set_index('date',inplace=True)
df

temperature  windspeed   city
date                                     
2017-01-01           32          6  patan
2017-02-01           85          7   ahem
2017-03-01           28          5  surat
2017-01-12           42          7  patan
2017-02-12           32          1   ahem
2017-03-12           51          6  surat
2017-01-02           75          8  patan
2017-02-02           94          9   ahem
2017-03-02           15          2  surat

In [142]:
def conver_event_cell(cell):
    if cell == 'No Event':
        return 'NaN'
    return cell

def conver_temp_cell(cell):
    if cell == -99999:
        return 'NaN'
    return cell

def conver_wind_cell(cell):
    if cell == 6:
        return 'NaN'
    return cell

df = pd.read_excel('E:/data science/data sets/whethers.xlsx',converters={
    'event':conver_event_cell,
    'temperature':conver_temp_cell,
    'windspeed':conver_wind_cell
})
df

date  temperature windspeed   city
0 2017-01-01           32       NaN  patan
1 2017-02-01           85         7   ahem
2 2017-03-01           28         5  surat
3 2017-01-12           42         7  patan
4 2017-02-12           32         1   ahem
5 2017-03-12           51       NaN  surat
6 2017-01-02           75         8  patan
7 2017-02-02           94         9   ahem
8 2017-03-02           15         2  surat

In [143]:
new = df.fillna(0)
new

date  temperature  windspeed   city
0 2017-01-01           32          0  patan
1 2017-02-01           85          7   ahem
2 2017-03-01           28          5  surat
3 2017-01-12           42          7  patan
4 2017-02-12           32          1   ahem
5 2017-03-12           51          0  surat
6 2017-01-02           75          8  patan
7 2017-02-02           94          9   ahem
8 2017-03-02           15          2  surat

In [144]:
new = df.fillna({
    'temperature':0,
    'windspeed':0,
    'event':'no event'
})

In [145]:
new

date  temperature  windspeed   city
0 2017-01-01           32          0  patan
1 2017-02-01           85          7   ahem
2 2017-03-01           28          5  surat
3 2017-01-12           42          7  patan
4 2017-02-12           32          1   ahem
5 2017-03-12           51          0  surat
6 2017-01-02           75          8  patan
7 2017-02-02           94          9   ahem
8 2017-03-02           15          2  surat

In [146]:
new = df.fillna(method='ffill',axis='columns')
new

date temperature windspeed   city
0 2017-01-01          32        32  patan
1 2017-02-01          85         7   ahem
2 2017-03-01          28         5  surat
3 2017-01-12          42         7  patan
4 2017-02-12          32         1   ahem
5 2017-03-12          51        51  surat
6 2017-01-02          75         8  patan
7 2017-02-02          94         9   ahem
8 2017-03-02          15         2  surat

In [147]:
new = df.fillna(method='bfill',axis='columns')
new

date temperature windspeed   city
0 2017-01-01          32     patan  patan
1 2017-02-01          85         7   ahem
2 2017-03-01          28         5  surat
3 2017-01-12          42         7  patan
4 2017-02-12          32         1   ahem
5 2017-03-12          51     surat  surat
6 2017-01-02          75         8  patan
7 2017-02-02          94         9   ahem
8 2017-03-02          15         2  surat

In [148]:
new = df.fillna(method='ffill',limit=2)
new

date  temperature  windspeed   city
0 2017-01-01           32        NaN  patan
1 2017-02-01           85        7.0   ahem
2 2017-03-01           28        5.0  surat
3 2017-01-12           42        7.0  patan
4 2017-02-12           32        1.0   ahem
5 2017-03-12           51        1.0  surat
6 2017-01-02           75        8.0  patan
7 2017-02-02           94        9.0   ahem
8 2017-03-02           15        2.0  surat

In [149]:
new = df.interpolate(method='time')
new

date  temperature windspeed   city
0 2017-01-01           32       NaN  patan
1 2017-02-01           85         7   ahem
2 2017-03-01           28         5  surat
3 2017-01-12           42         7  patan
4 2017-02-12           32         1   ahem
5 2017-03-12           51       NaN  surat
6 2017-01-02           75         8  patan
7 2017-02-02           94         9   ahem
8 2017-03-02           15         2  surat

In [150]:
new = df.dropna()
new

date  temperature windspeed   city
1 2017-02-01           85         7   ahem
2 2017-03-01           28         5  surat
3 2017-01-12           42         7  patan
4 2017-02-12           32         1   ahem
6 2017-01-02           75         8  patan
7 2017-02-02           94         9   ahem
8 2017-03-02           15         2  surat

In [151]:
new = df.dropna(how='all')
new

date  temperature windspeed   city
0 2017-01-01           32       NaN  patan
1 2017-02-01           85         7   ahem
2 2017-03-01           28         5  surat
3 2017-01-12           42         7  patan
4 2017-02-12           32         1   ahem
5 2017-03-12           51       NaN  surat
6 2017-01-02           75         8  patan
7 2017-02-02           94         9   ahem
8 2017-03-02           15         2  surat

In [152]:
new = df.dropna(thresh=1)
new

date  temperature windspeed   city
0 2017-01-01           32       NaN  patan
1 2017-02-01           85         7   ahem
2 2017-03-01           28         5  surat
3 2017-01-12           42         7  patan
4 2017-02-12           32         1   ahem
5 2017-03-12           51       NaN  surat
6 2017-01-02           75         8  patan
7 2017-02-02           94         9   ahem
8 2017-03-02           15         2  surat

In [153]:
new = df.dropna(thresh=2)
new

date  temperature windspeed   city
0 2017-01-01           32       NaN  patan
1 2017-02-01           85         7   ahem
2 2017-03-01           28         5  surat
3 2017-01-12           42         7  patan
4 2017-02-12           32         1   ahem
5 2017-03-12           51       NaN  surat
6 2017-01-02           75         8  patan
7 2017-02-02           94         9   ahem
8 2017-03-02           15         2  surat

In [157]:
dt = pd.date_range('2017/1/1','2017/1/11')
idx = pd.DatetimeIndex(dt)
df = df.reindex(idx)
df

date  temperature windspeed city
2017-01-01  NaT          NaN       NaN  NaN
2017-01-02  NaT          NaN       NaN  NaN
2017-01-03  NaT          NaN       NaN  NaN
2017-01-04  NaT          NaN       NaN  NaN
2017-01-05  NaT          NaN       NaN  NaN
2017-01-06  NaT          NaN       NaN  NaN
2017-01-07  NaT          NaN       NaN  NaN
2017-01-08  NaT          NaN       NaN  NaN
2017-01-09  NaT          NaN       NaN  NaN
2017-01-10  NaT          NaN       NaN  NaN
2017-01-11  NaT          NaN       NaN  NaN

In [158]:
df = pd.read_excel('E:/data science/data sets/whethers.xlsx',parse_dates=['date'])
df

date  temperature  windspeed   city
0 2017-01-01           32          6  patan
1 2017-02-01           85          7   ahem
2 2017-03-01           28          5  surat
3 2017-01-12           42          7  patan
4 2017-02-12           32          1   ahem
5 2017-03-12           51          6  surat
6 2017-01-02           75          8  patan
7 2017-02-02           94          9   ahem
8 2017-03-02           15          2  surat

In [159]:
new_df = df.replace([-99999,-88888,0],np.NaN)
new_df

date  temperature  windspeed   city
0 2017-01-01           32          6  patan
1 2017-02-01           85          7   ahem
2 2017-03-01           28          5  surat
3 2017-01-12           42          7  patan
4 2017-02-12           32          1   ahem
5 2017-03-12           51          6  surat
6 2017-01-02           75          8  patan
7 2017-02-02           94          9   ahem
8 2017-03-02           15          2  surat

In [160]:
new_df = df.replace({
    'temperature':-99999,
    'windspeed':-88888,
    'event':0
},np.NaN)
new_df

date  temperature  windspeed   city
0 2017-01-01           32          6  patan
1 2017-02-01           85          7   ahem
2 2017-03-01           28          5  surat
3 2017-01-12           42          7  patan
4 2017-02-12           32          1   ahem
5 2017-03-12           51          6  surat
6 2017-01-02           75          8  patan
7 2017-02-02           94          9   ahem
8 2017-03-02           15          2  surat

In [161]:
new_df = df.replace({
    'temperature':-99999,
    'windspeed':-88888,
    'event':'No Event'
})
new_df

date  temperature  windspeed   city
0 2017-01-01           32          6  patan
1 2017-02-01           85          7   ahem
2 2017-03-01           28          5  surat
3 2017-01-12           42          7  patan
4 2017-02-12           32          1   ahem
5 2017-03-12           51          6  surat
6 2017-01-02           75          8  patan
7 2017-02-02           94          9   ahem
8 2017-03-02           15          2  surat

In [162]:
new_df = df.replace({
          -99999:np.NaN,
          0:'modi'
})
new_df

date  temperature  windspeed   city
0 2017-01-01           32          6  patan
1 2017-02-01           85          7   ahem
2 2017-03-01           28          5  surat
3 2017-01-12           42          7  patan
4 2017-02-12           32          1   ahem
5 2017-03-12           51          6  surat
6 2017-01-02           75          8  patan
7 2017-02-02           94          9   ahem
8 2017-03-02           15          2  surat

In [163]:
new_df = df.replace({
          32:'32 F',
          75: '32 C',
          6:'Abc'
})
new_df

date temperature windspeed   city
0 2017-01-01        32 F       Abc  patan
1 2017-02-01          85         7   ahem
2 2017-03-01          28         5  surat
3 2017-01-12          42         7  patan
4 2017-02-12        32 F         1   ahem
5 2017-03-12          51       Abc  surat
6 2017-01-02        32 C         8  patan
7 2017-02-02          94         9   ahem
8 2017-03-02          15         2  surat

In [164]:
new_df = df.replace('[A-Za-z]','',regex=True) #jya jetla pan letter hase ae remove thei jase
new_df

date  temperature  windspeed city
0 2017-01-01           32          6     
1 2017-02-01           85          7     
2 2017-03-01           28          5     
3 2017-01-12           42          7     
4 2017-02-12           32          1     
5 2017-03-12           51          6     
6 2017-01-02           75          8     
7 2017-02-02           94          9     
8 2017-03-02           15          2

In [165]:
new_df = df.replace({
    'temperature':'[A-Za-z]',
    'windspeed':'[A-Za-z]'
},'',regex=True) #apde specific columns na letters change karva mate dictionary no use thy
new_df

date  temperature  windspeed   city
0 2017-01-01           32          6  patan
1 2017-02-01           85          7   ahem
2 2017-03-01           28          5  surat
3 2017-01-12           42          7  patan
4 2017-02-12           32          1   ahem
5 2017-03-12           51          6  surat
6 2017-01-02           75          8  patan
7 2017-02-02           94          9   ahem
8 2017-03-02           15          2  surat

In [166]:
#list in tuples

weather_data = [
    ('1/1/2017',85,45,'rain'),
    ('1/2/2017',45,'NaN','sunny'),
    ('1/3/2017',75,94,'modi'),
    ('1/4/2017',95,71,'NaN'),
    ('NaN',65,21,'dipu'),
    ('1/6/2017',95,41,'NaN'),
    ('1/7/2018',85,64,'sila'),
    ('1/9/2019','NaN',35,'muni')
]
df = pd.DataFrame(weather_data,columns=['day','temperature','winspeed','event'])
df

day temperature winspeed  event
0  1/1/2017          85       45   rain
1  1/2/2017          45      NaN  sunny
2  1/3/2017          75       94   modi
3  1/4/2017          95       71    NaN
4       NaN          65       21   dipu
5  1/6/2017          95       41    NaN
6  1/7/2018          85       64   sila
7  1/9/2019         NaN       35   muni

In [167]:
df1 = df.replace(['rain','modi','sila'],[55,82,73])
df1

day temperature winspeed  event
0  1/1/2017          85       45     55
1  1/2/2017          45      NaN  sunny
2  1/3/2017          75       94     82
3  1/4/2017          95       71    NaN
4       NaN          65       21   dipu
5  1/6/2017          95       41    NaN
6  1/7/2018          85       64     73
7  1/9/2019         NaN       35   muni

In [169]:
df = pd.read_excel('E:/data science/data sets/whethers.xlsx',parse_dates=['date'])
df

date  temperature  windspeed   city
0 2017-01-01           32          6  patan
1 2017-02-01           85          7   ahem
2 2017-03-01           28          5  surat
3 2017-01-12           42          7  patan
4 2017-02-12           32          1   ahem
5 2017-03-12           51          6  surat
6 2017-01-02           75          8  patan
7 2017-02-02           94          9   ahem
8 2017-03-02           15          2  surat

In [170]:
g = df.groupby('city')
g

In [180]:
for city in g:
    print(city)

('ahem',         date  temperature  windspeed  city
1 2017-02-01           85          7  ahem
4 2017-02-12           32          1  ahem
7 2017-02-02           94          9  ahem)
('patan',         date  temperature  windspeed   city
0 2017-01-01           32          6  patan
3 2017-01-12           42          7  patan
6 2017-01-02           75          8  patan)
('surat',         date  temperature  windspeed   city
2 2017-03-01           28          5  surat
5 2017-03-12           51          6  surat
8 2017-03-02           15          2  surat)


In [176]:
g.get_group('patan')

date  temperature  windspeed   city
0 2017-01-01           32          6  patan
3 2017-01-12           42          7  patan
6 2017-01-02           75          8  patan

In [177]:
g.max()   #hi temperature in city

date  temperature  windspeed
city                                    
ahem  2017-02-12           94          9
patan 2017-01-12           75          8
surat 2017-03-12           51          6

In [178]:
g.mean()  #split average and combine is mean method

temperature  windspeed
city                         
ahem     70.333333   5.666667
patan    49.666667   7.000000
surat    31.333333   4.333333

In [179]:
g.describe()

temperature                                                      \
            count       mean        std   min   25%   50%   75%   max   
city                                                                    
ahem          3.0  70.333333  33.501244  32.0  58.5  85.0  89.5  94.0   
patan         3.0  49.666667  22.501852  32.0  37.0  42.0  58.5  75.0   
surat         3.0  31.333333  18.230012  15.0  21.5  28.0  39.5  51.0   

      windspeed                                               
          count      mean       std  min  25%  50%  75%  max  
city                                                          
ahem        3.0  5.666667  4.163332  1.0  4.0  7.0  8.0  9.0  
patan       3.0  7.000000  1.000000  6.0  6.5  7.0  7.5  8.0  
surat       3.0  4.333333  2.081666  2.0  3.5  5.0  5.5  6.0

In [181]:
df = pd.DataFrame({
    'city':['new york','canada','australiya'],
    'tempe':[85,42,61],
    'population':[52,12,31],
    'growth':[5,3,1]
},index=[1,2,3])
df

city  tempe  population  growth
1    new york     85          52       5
2      canada     42          12       3
3  australiya     61          31       1

In [182]:
df1 = pd.DataFrame({
    'city':['india','gujarat','patan'],
    'tempe':[58,24,16],
    'gdp':[25,21,13]
},index=[4,5,6])
df1

city  tempe  gdp
4    india     58   25
5  gujarat     24   21
6    patan     16   13

In [183]:
df2 = pd.concat([df,df1],ignore_index=True) # index is line by line 
df2

city  tempe  population  growth   gdp
0    new york     85        52.0     5.0   NaN
1      canada     42        12.0     3.0   NaN
2  australiya     61        31.0     1.0   NaN
3       india     58         NaN     NaN  25.0
4     gujarat     24         NaN     NaN  21.0
5       patan     16         NaN     NaN  13.0

In [184]:
df2 = pd.concat([df,df1],keys=['america','india1']) # index is line by line 
df2

city  tempe  population  growth   gdp
america 1    new york     85        52.0     5.0   NaN
        2      canada     42        12.0     3.0   NaN
        3  australiya     61        31.0     1.0   NaN
india1  4       india     58         NaN     NaN  25.0
        5     gujarat     24         NaN     NaN  21.0
        6       patan     16         NaN     NaN  13.0

In [185]:
df2.loc['america']

city  tempe  population  growth  gdp
1    new york     85        52.0     5.0  NaN
2      canada     42        12.0     3.0  NaN
3  australiya     61        31.0     1.0  NaN

In [186]:
df2 = pd.concat([df,df1],axis=1)
df2

city  tempe  population  growth     city  tempe   gdp
1    new york   85.0        52.0     5.0      NaN    NaN   NaN
2      canada   42.0        12.0     3.0      NaN    NaN   NaN
3  australiya   61.0        31.0     1.0      NaN    NaN   NaN
4         NaN    NaN         NaN     NaN    india   58.0  25.0
5         NaN    NaN         NaN     NaN  gujarat   24.0  21.0
6         NaN    NaN         NaN     NaN    patan   16.0  13.0

In [187]:
df2 = pd.concat([df,df1],axis=0)
df2

city  tempe  population  growth   gdp
1    new york     85        52.0     5.0   NaN
2      canada     42        12.0     3.0   NaN
3  australiya     61        31.0     1.0   NaN
4       india     58         NaN     NaN  25.0
5     gujarat     24         NaN     NaN  21.0
6       patan     16         NaN     NaN  13.0

In [188]:
s = pd.Series(['humid','Dry','Rain'],name='event')
s

0    humid
1      Dry
2     Rain
Name: event, dtype: object

In [189]:
df = pd.concat([df2,s],axis=1)
df

city  tempe  population  growth   gdp  event
0         NaN    NaN         NaN     NaN   NaN  humid
1    new york   85.0        52.0     5.0   NaN    Dry
2      canada   42.0        12.0     3.0   NaN   Rain
3  australiya   61.0        31.0     1.0   NaN    NaN
4       india   58.0         NaN     NaN  25.0    NaN
5     gujarat   24.0         NaN     NaN  21.0    NaN
6       patan   16.0         NaN     NaN  13.0    NaN

In [190]:
df = pd.DataFrame({
    'city':['new york','canada','australiya'],
    'tempe':[85,42,61],
    'population':[52,12,31],
})
df

city  tempe  population
0    new york     85          52
1      canada     42          12
2  australiya     61          31

In [191]:
df1 = pd.DataFrame({
    'city':['new york','canada','australiya','snafransisco','califoniya'],
    'humid':[58,24,16,75,61],
})
df1

city  humid
0      new york     58
1        canada     24
2    australiya     16
3  snafransisco     75
4    califoniya     61

In [192]:
df2 = pd.merge(df,df1,on='city',how='outer',indicator=True)
df2

city  tempe  population  humid      _merge
0      new york   85.0        52.0     58        both
1        canada   42.0        12.0     24        both
2    australiya   61.0        31.0     16        both
3  snafransisco    NaN         NaN     75  right_only
4    califoniya    NaN         NaN     61  right_only

In [193]:
df2 = pd.merge(df,df1,on='city',how='inner')
df2

city  tempe  population  humid
0    new york     85          52     58
1      canada     42          12     24
2  australiya     61          31     16

In [194]:
df2 = pd.merge(df,df1,on='city',how='right')
df2

city  tempe  population  humid
0      new york   85.0        52.0     58
1        canada   42.0        12.0     24
2    australiya   61.0        31.0     16
3  snafransisco    NaN         NaN     75
4    califoniya    NaN         NaN     61

In [195]:
df = pd.DataFrame({
    'city':['new york','canada','australiya','chicago','landon'],
    'tempe':[85,42,61,94,62],
    'humid':[52,12,31,13,52]
})
df

city  tempe  humid
0    new york     85     52
1      canada     42     12
2  australiya     61     31
3     chicago     94     13
4      landon     62     52

In [196]:
df1 = pd.DataFrame({
    'city':['new york','snafransisco','califoniya'],
    'humid':[58,24,16]
})
df1

city  humid
0      new york     58
1  snafransisco     24
2    califoniya     16

In [197]:
df2 = pd.merge(df,df1,on='city',suffixes=('_left','_right'))
df2

city  tempe  humid_left  humid_right
0  new york     85          52           58

In [199]:
df = pd.read_excel('E:/data science/data sets/whethers.xlsx',parse_dates=['date'])
df

date  temperature  windspeed   city
0 2017-01-01           32          6  patan
1 2017-02-01           85          7   ahem
2 2017-03-01           28          5  surat
3 2017-01-12           42          7  patan
4 2017-02-12           32          1   ahem
5 2017-03-12           51          6  surat
6 2017-01-02           75          8  patan
7 2017-02-02           94          9   ahem
8 2017-03-02           15          2  surat

In [200]:
df.pivot_table(index='date',columns='city',values='temperature')

city        ahem  patan  surat
date                          
2017-01-01   NaN   32.0    NaN
2017-01-02   NaN   75.0    NaN
2017-01-12   NaN   42.0    NaN
2017-02-01  85.0    NaN    NaN
2017-02-02  94.0    NaN    NaN
2017-02-12  32.0    NaN    NaN
2017-03-01   NaN    NaN   28.0
2017-03-02   NaN    NaN   15.0
2017-03-12   NaN    NaN   51.0

In [201]:
df.pivot_table(index='city',columns='date',margins=True)

temperature                                          \
date  2017-01-01 00:00:00 2017-01-02 00:00:00 2017-01-12 00:00:00   
city                                                                
ahem                  NaN                 NaN                 NaN   
patan                32.0                75.0                42.0   
surat                 NaN                 NaN                 NaN   
All                  32.0                75.0                42.0   

                                                                   \
date  2017-02-01 00:00:00 2017-02-02 00:00:00 2017-02-12 00:00:00   
city                                                                
ahem                 85.0                94.0                32.0   
patan                 NaN                 NaN                 NaN   
surat                 NaN                 NaN                 NaN   
All                  85.0                94.0                32.0   

                                                                              \
date  2017-03-01 00:00:00 2017-03-02 00:00:00 2017-03-12 00:00:00        All   
city                                                                           
ahem                  NaN                 NaN                 NaN  70.333333   
patan                 NaN                 NaN                 NaN  49.666667   
surat                28.0                15.0                51.0  31.333333   
All                  28.0                15.0                51.0  50.444444   

                windspeed                                          \
date  2017-01-01 00:00:00 2017-01-02 00:00:00 2017-01-12 00:00:00   
city                                                                
ahem                  NaN                 NaN                 NaN   
patan                 6.0                 8.0                 7.0   
surat                 NaN                 NaN                 NaN   
All                   6.0                 8.0                 7.0   

                                                                   \
date  2017-02-01 00:00:00 2017-02-02 00:00:00 2017-02-12 00:00:00   
city                                                                
ahem                  7.0                 9.0                 1.0   
patan                 NaN                 NaN                 NaN   
surat                 NaN                 NaN                 NaN   
All                   7.0                 9.0                 1.0   

                                                                             
date  2017-03-01 00:00:00 2017-03-02 00:00:00 2017-03-12 00:00:00       All  
city                                                                         
ahem                  NaN                 NaN                 NaN  5.666667  
patan                 NaN                 NaN                 NaN  7.000000  
surat                 5.0                 2.0                 6.0  4.333333  
All                   5.0                 2.0                 6.0  5.666667

In [202]:
df.pivot(index='city',columns='date')

temperature                                                         \
date   2017-01-01 2017-01-02 2017-01-12 2017-02-01 2017-02-02 2017-02-12   
city                                                                       
ahem          NaN        NaN        NaN       85.0       94.0       32.0   
patan        32.0       75.0       42.0        NaN        NaN        NaN   
surat         NaN        NaN        NaN        NaN        NaN        NaN   

                                        windspeed                        \
date  2017-03-01 2017-03-02 2017-03-12 2017-01-01 2017-01-02 2017-01-12   
city                                                                      
ahem         NaN        NaN        NaN        NaN        NaN        NaN   
patan        NaN        NaN        NaN        6.0        8.0        7.0   
surat       28.0       15.0       51.0        NaN        NaN        NaN   

                                                                         
date  2017-02-01 2017-02-02 2017-02-12 2017-03-01 2017-03-02 2017-03-12  
city                                                                     
ahem         7.0        9.0        1.0        NaN        NaN        NaN  
patan        NaN        NaN        NaN        NaN        NaN        NaN  
surat        NaN        NaN        NaN        5.0        2.0        6.0

In [203]:
df['date']=pd.to_datetime(df.date)

In [204]:
df

date  temperature  windspeed   city
0 2017-01-01           32          6  patan
1 2017-02-01           85          7   ahem
2 2017-03-01           28          5  surat
3 2017-01-12           42          7  patan
4 2017-02-12           32          1   ahem
5 2017-03-12           51          6  surat
6 2017-01-02           75          8  patan
7 2017-02-02           94          9   ahem
8 2017-03-02           15          2  surat

In [205]:
df1 = pd.melt(df,id_vars=['date'])
df1

date     variable  value
0  2017-01-01  temperature     32
1  2017-02-01  temperature     85
2  2017-03-01  temperature     28
3  2017-01-12  temperature     42
4  2017-02-12  temperature     32
5  2017-03-12  temperature     51
6  2017-01-02  temperature     75
7  2017-02-02  temperature     94
8  2017-03-02  temperature     15
9  2017-01-01    windspeed      6
10 2017-02-01    windspeed      7
11 2017-03-01    windspeed      5
12 2017-01-12    windspeed      7
13 2017-02-12    windspeed      1
14 2017-03-12    windspeed      6
15 2017-01-02    windspeed      8
16 2017-02-02    windspeed      9
17 2017-03-02    windspeed      2
18 2017-01-01         city  patan
19 2017-02-01         city   ahem
20 2017-03-01         city  surat
21 2017-01-12         city  patan
22 2017-02-12         city   ahem
23 2017-03-12         city  surat
24 2017-01-02         city  patan
25 2017-02-02         city   ahem
26 2017-03-02         city  surat

In [206]:
df1[df1.variable=='temperature']

date     variable value
0 2017-01-01  temperature    32
1 2017-02-01  temperature    85
2 2017-03-01  temperature    28
3 2017-01-12  temperature    42
4 2017-02-12  temperature    32
5 2017-03-12  temperature    51
6 2017-01-02  temperature    75
7 2017-02-02  temperature    94
8 2017-03-02  temperature    15

In [207]:
df1 = pd.melt(df,id_vars=['date'],var_name='city',value_name='temperature')
df1

date         city temperature
0  2017-01-01  temperature          32
1  2017-02-01  temperature          85
2  2017-03-01  temperature          28
3  2017-01-12  temperature          42
4  2017-02-12  temperature          32
5  2017-03-12  temperature          51
6  2017-01-02  temperature          75
7  2017-02-02  temperature          94
8  2017-03-02  temperature          15
9  2017-01-01    windspeed           6
10 2017-02-01    windspeed           7
11 2017-03-01    windspeed           5
12 2017-01-12    windspeed           7
13 2017-02-12    windspeed           1
14 2017-03-12    windspeed           6
15 2017-01-02    windspeed           8
16 2017-02-02    windspeed           9
17 2017-03-02    windspeed           2
18 2017-01-01         city       patan
19 2017-02-01         city        ahem
20 2017-03-01         city       surat
21 2017-01-12         city       patan
22 2017-02-12         city        ahem
23 2017-03-12         city       surat
24 2017-01-02         city       patan
25 2017-02-02         city        ahem
26 2017-03-02         city       surat

In [208]:
df1 = df.stack(level=0) #ano use jayare  2 headwers hoy are thy
df1

0  date           2017-01-01 00:00:00
   temperature                     32
   windspeed                        6
   city                         patan
1  date           2017-02-01 00:00:00
   temperature                     85
   windspeed                        7
   city                          ahem
2  date           2017-03-01 00:00:00
   temperature                     28
   windspeed                        5
   city                         surat
3  date           2017-01-12 00:00:00
   temperature                     42
   windspeed                        7
   city                         patan
4  date           2017-02-12 00:00:00
   temperature                     32
   windspeed                        1
   city                          ahem
5  date           2017-03-12 00:00:00
   temperature                     51
   windspeed                        6
   city                         surat
6  date           2017-01-02 00:00:00
   temperature                     75
   windspeed

In [209]:
df1.unstack()

date temperature windspeed   city
0 2017-01-01          32         6  patan
1 2017-02-01          85         7   ahem
2 2017-03-01          28         5  surat
3 2017-01-12          42         7  patan
4 2017-02-12          32         1   ahem
5 2017-03-12          51         6  surat
6 2017-01-02          75         8  patan
7 2017-02-02          94         9   ahem
8 2017-03-02          15         2  surat

In [210]:
pd.crosstab(df.date,df.city,margins=True)

city                 ahem  patan  surat  All
date                                        
2017-01-01 00:00:00     0      1      0    1
2017-01-02 00:00:00     0      1      0    1
2017-01-12 00:00:00     0      1      0    1
2017-02-01 00:00:00     1      0      0    1
2017-02-02 00:00:00     1      0      0    1
2017-02-12 00:00:00     1      0      0    1
2017-03-01 00:00:00     0      0      1    1
2017-03-02 00:00:00     0      0      1    1
2017-03-12 00:00:00     0      0      1    1
All                     3      3      3    9

In [211]:
pd.crosstab(df.date,df.city,normalize='index')

city        ahem  patan  surat
date                          
2017-01-01   0.0    1.0    0.0
2017-01-02   0.0    1.0    0.0
2017-01-12   0.0    1.0    0.0
2017-02-01   1.0    0.0    0.0
2017-02-02   1.0    0.0    0.0
2017-02-12   1.0    0.0    0.0
2017-03-01   0.0    0.0    1.0
2017-03-02   0.0    0.0    1.0
2017-03-12   0.0    0.0    1.0

In [212]:
pd.crosstab(df.date,df.city,values=df.temperature,aggfunc=np.average)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\function_base.py:393: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


city        ahem  patan  surat
date                          
2017-01-01   NaN   32.0    NaN
2017-01-02   NaN   75.0    NaN
2017-01-12   NaN   42.0    NaN
2017-02-01  85.0    NaN    NaN
2017-02-02  94.0    NaN    NaN
2017-02-12  32.0    NaN    NaN
2017-03-01   NaN    NaN   28.0
2017-03-02   NaN    NaN   15.0
2017-03-12   NaN    NaN   51.0